### ISSUE TITLE
Composer bug

### ISSUE THREAD

**Issue by F0rest-csgo** [HaoZi-Team/ChatGPT-PHP#1]
When I Composing this it shows:Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json

**Comment by devhaozi** [comment]
I tested in Laravel but didn't find this problem, can you provide more information?

**Comment by F0rest-csgo** [comment]
宝塔面板网站composer
Downloading https://mirrors.cloud.tencent.com/composer/packages.json
[200] https://mirrors.cloud.tencent.com/composer/packages.json
Writing /home/www/.cache/composer/repo/https---mirrors.cloud.tencent.com-composer/packages.json into cache
Downloading https://mirrors.tencent.com/repository/composer/p/haozi-team/chatgpt-php.json
[200] https://mirrors.tencent.com/repository/composer/p/haozi-team/chatgpt-php.json
Writing /home/www/.cache/composer/repo/https---mirrors.cloud.tencent.com-composer/provider-haozi-team$chatgpt-php.json into cache
Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json

**Comment by devhaozi** [comment]
Looks like TencentCloud composer mirrors doesn't up to date. Try to use https://repo.packagist.org

**Comment by F0rest-csgo** [comment]
Downloading https://repo.packagist.org/packages.json if modified
[200] https://repo.packagist.org/packages.json
Info from https://repo.packagist.org: #StandWithUkraine
Writing /home/www/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Reading /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json from cache
Downloading https://repo.packagist.org/p2/haozi-team/chatgpt-php.json if modified
[200] https://repo.packagist.org/p2/haozi-team/chatgpt-php.json
Writing /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json into cache
Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json
Same

**Comment by devhaozi** [comment]
> Downloading https://repo.packagist.org/packages.json if modified [200] https://repo.packagist.org/packages.json Info from https://repo.packagist.org: #StandWithUkraine Writing /home/www/.cache/composer/repo/https---repo.packagist.org/packages.json into cache Reading /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json from cache Downloading https://repo.packagist.org/p2/haozi-team/chatgpt-php.json if modified [200] https://repo.packagist.org/p2/haozi-team/chatgpt-php.json Writing /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json into cache Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json Same

I delete composer.lock file, Try again.

**Comment by F0rest-csgo** [comment]
> > Downloading https://repo.packagist.org/packages.json if modified [200] https://repo.packagist.org/packages.json Info from https://repo.packagist.org: #StandWithUkraine Writing /home/www/.cache/composer/repo/https---repo.packagist.org/packages.json into cache Reading /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json from cache Downloading https://repo.packagist.org/p2/haozi-team/chatgpt-php.json if modified [200] https://repo.packagist.org/p2/haozi-team/chatgpt-php.json Writing /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json into cache Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json Same
> 
> I delete composer.lock file, Try again.


Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Info from https://repo.packagist.org: #StandWithUkraine
Writing /home/www/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Downloading https://repo.packagist.org/p2/haozi-team/chatgpt-php.json
[200] https://repo.packagist.org/p2/haozi-team/chatgpt-php.json
Writing /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json into cache
Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json
Still not working.
I Googled it and looks like the name in composer.json was same with the package's require

**Comment by devhaozi** [comment]
> > > Downloading https://repo.packagist.org/packages.json if modified [200] https://repo.packagist.org/packages.json Info from https://repo.packagist.org: #StandWithUkraine Writing /home/www/.cache/composer/repo/https---repo.packagist.org/packages.json into cache Reading /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json from cache Downloading https://repo.packagist.org/p2/haozi-team/chatgpt-php.json if modified [200] https://repo.packagist.org/p2/haozi-team/chatgpt-php.json Writing /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json into cache Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json Same
> > 
> > 
> > I delete composer.lock file, Try again.
> 
> Downloading https://repo.packagist.org/packages.json [200] https://repo.packagist.org/packages.json Info from https://repo.packagist.org: #StandWithUkraine Writing /home/www/.cache/composer/repo/https---repo.packagist.org/packages.json into cache Downloading https://repo.packagist.org/p2/haozi-team/chatgpt-php.json [200] https://repo.packagist.org/p2/haozi-team/chatgpt-php.json Writing /home/www/.cache/composer/repo/https---repo.packagist.org/provider-haozi-team~chatgpt-php.json into cache Root package 'haozi-team/chatgpt-php' cannot require itself in its composer.json Still not working. I Googled it and looks like the name in composer.json was same with the package's require

You can check my repo. I doesn't do it.

**Comment by F0rest-csgo** [comment]
Sorry,It's my fault.I run this with composer.json in the folder.
