### ISSUE TITLE
Ask for documentation 

### ISSUE THREAD

**Issue by CatAnonymous** [HaoZi-Team/ChatGPT-PHP#11]
I see in ChatGPT for iOS version there is chat without save to history, can you guide me to enable it on your V1 version?
![77A5C526-A8FE-48B4-95AA-2DD5CB003CB8](https://github.com/HaoZi-Team/ChatGPT-PHP/assets/25249169/90c23a12-a661-4707-b3cd-7538766efc38)
![32E0144F-2B00-44EF-82B4-9EAC6F580FCB](https://github.com/HaoZi-Team/ChatGPT-PHP/assets/25249169/aa3719a6-3371-4e70-ba11-37e2e572f807)

**Comment by devhaozi** [comment]
V1 is built based on WEB API, it is not clear whether IOS APP uses WEB API, and V1 current does not support operation history switch, I will try to add it when I am free.

**Comment by CatAnonymous** [comment]
> V1 is built based on WEB API, it is not clear whether IOS APP uses WEB API, and V1 current does not support operation history switch, I will try to add it when I am free.

 it is available in both WEB version

**Comment by devhaozi** [comment]
> > V1 is built based on WEB API, it is not clear whether IOS APP uses WEB API, and V1 current does not support operation history switch, I will try to add it when I am free.
> 
> it is available in both WEB version

Added it.
