### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by themw123** [HaoZi-Team/ChatGPT-PHP#12]
I am getting the following error using V1:
GuzzleHttp\Exception\ServerException: Server error: `POST https://ai.fakeopen.com/api/conversation` resulted in a `500 Internal Server Error` response

Is it because of the fact that the proxy is down?

**Comment by devhaozi** [comment]
Yes, it looks like the proxy server is down, please wait for it to be fixed or you can try another server `https://bypass.churchless.tech/`
