### ISSUE TITLE
Continue generating with v1

### ISSUE THREAD

**Issue by WinInstall** [HaoZi-Team/ChatGPT-PHP#13]
Often the answers are not complete and need to continue to generate, the web version has a button for this, but to send a response as "continue" very often does not lead to the results, which would be desirable

**Comment by devhaozi** [comment]
> Often the answers are not complete and need to continue to generate, the web version has a button for this, but to send a response as "continue" very often does not lead to the results, which would be desirable

Yes, but I'm busy with exams right now, I'll add support when I'm free. Maybe before August.

**Comment by devhaozi** [comment]
This functionality is currently implemented, but not fully tested. Current call `ask` will return `finish_details`, and determine whether to call `continueWrite` by judging it.
