### ISSUE TITLE
老哥好啊，终于更新了

### ISSUE THREAD

**Issue by 18230** [HaoZi-Team/ChatGPT-PHP#14]
有个问题，
就是我换成 $chatGPT = new ChatGPTV1('https://chat.openai.com/backend-api/');  好像无效

**Comment by devhaozi** [comment]
> 有个问题， 就是我换成 $chatGPT = new ChatGPTV1('https://chat.openai.com/backend-api/'); 好像无效

官网有cloudflare保护，你需要自行反代绕过。
参考：github.com/acheong08/ChatGPTProxy

**Comment by 18230** [comment]
> > 有个问题， 就是我换成 $chatGPT = new ChatGPTV1('https://chat.openai.com/backend-api/'); 好像无效
> 
> 官网有cloudflare保护，你需要自行反代绕过。 参考：github.com/acheong08/ChatGPTProxy

对，我直接用的美国服务器，用08佬的go-chatgpt-api可以，换这个好像不行，没有返回值

**Comment by 18230** [comment]
老哥有空搞个php版的，哈哈

**Comment by devhaozi** [comment]
> 老哥有空搞个php版的，哈哈

没必要，性能低效且麻烦。
