### ISSUE TITLE
getting Exception in V1.php

### ISSUE THREAD

**Issue by themw123** [HaoZi-Team/ChatGPT-PHP#15]
I am using php 8.2.0 and haozi-team/chatgpt-php 2.1.0. Also i am using chatgpt 3.5 without premium.

V1
Line:
if (substr($this->accounts[$name]['model'], 0, 5) === 'gpt-4' && $arkoseToken === null) {

Error:
Exception occurred.
Warning: Undefined array key ""

and some more warnings and deprecaded alerts

**Comment by sohenk** [comment]
same

**Comment by devhaozi** [comment]
Fixed in 2.1.1.

**Comment by themw123** [comment]
Thank you for fixing, but now i am getting another deprecated and warning in V1.php 

line 53: if (substr($this->accounts[count($this->accounts) - 1]['model'], 0, 5) === 'gpt-4' && $arkoseToken === null) {
Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated

line 183: 'model' => empty($this->accounts[$account]['model']) ? $this->accounts[$account]['paid'] ? 'text-davinci-002-render-paid' : 'text-davinci-002-render-sha' : $this->accounts[$account]['model'],
Warning: Undefined array key "paid"

**Comment by devhaozi** [comment]
> Thank you for fixing, but now i am getting another deprecated and warning in V1.php
> 
> line 53: if (substr($this->accounts[count($this->accounts) - 1]['model'], 0, 5) === 'gpt-4' && $arkoseToken === null) { Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated
> 
> line 183: 'model' => empty($this->accounts[$account]['model']) ? $this->accounts[$account]['paid'] ? 'text-davinci-002-render-paid' : 'text-davinci-002-render-sha' : $this->accounts[$account]['model'], Warning: Undefined array key "paid"

fixed. run `composer update`
