### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by lukexp** [HaoZi-Team/ChatGPT-PHP#16]
I can't get it to work, it just returns Too Many Requests and the following message: "It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"

**Comment by devhaozi** [comment]
> I can't get it to work, it just returns Too Many Requests and the following message: "It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"

The web API has dead. You can refer to its tips to run a Pandora-Next as an API server.

![图片](https://github.com/haozi-team/ChatGPT-PHP/assets/115467771/4b1a9c65-b7ef-45a2-a397-01dddf56966a)
