### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function HaoziTeam\ChatGPT\V2::__construct(), 

### ISSUE THREAD

**Issue by hhfmiirvaxb943** [HaoZi-Team/ChatGPT-PHP#2]
<?php

require './src/V2.php';
use HaoziTeam\ChatGPT\V2 as ChatGPTV2;

$chatGPT = new ChatGPTV2('sk-1');

$chatGPT->addMessage('You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.', 'system');

$answer = $chatGPT->ask('Hello, how are you?');
print_r($answer);

**Comment by hhfmiirvaxb943** [comment]
`require './src/V2.php';
use HaoziTeam\ChatGPT\V2 as ChatGPTV2;

$chatGPT = new ChatGPTV2('sk-1');

$chatGPT->addMessage('You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.', 'system');

$answer = $chatGPT->ask('Hello, how are you?');
print_r($answer);`

**Comment by devhaozi** [comment]
Sorry, I made a mistake. I will fix it soon.

**Comment by devhaozi** [comment]
> Sorry, I made a mistake. I will fix it soon.

Fixed in 1.4.1.
