### ISSUE TITLE
必须要php8.1才能运行吗？能不能向下兼容下

### ISSUE THREAD

**Issue by hhfmiirvaxb943** [HaoZi-Team/ChatGPT-PHP#6]
7以上或者5.6以上

**Comment by devhaozi** [comment]
> 7以上或者5.6以上

最低要求php8.0。要向下兼容的话你可以fork下来去掉强类型应该就可以了。

**Comment by hhfmiirvaxb943** [comment]
不会啊

**Comment by devhaozi** [comment]
> 不会啊

hi, 目前已经向下兼容至php7.4。

**Comment by hhfmiirvaxb943** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - haozi-team/chatgpt-php[1.0.0, ..., 1.5.3] require php >=8.0 -> your php version (7.4.33) does not satisfy that requirement.
    - haozi-team/chatgpt-php[1.6.0, ..., 1.7.0] require guzzlehttp/guzzle ^7.2.0 -> found guzzlehttp/guzzle[7.2.0, ..., 7.5.0] but it conflicts with your root composer.json require (~6.0).
    - Root composer.json requires haozi-team/chatgpt-php * -> satisfiable by haozi-team/chatgpt-php[1.0.0, ..., 1.7.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require haozi-team/chatgpt-php:*" to figure out if any version is installable, or "composer require haozi-team/chatgpt-php:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by devhaozi** [comment]
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1 - haozi-team/chatgpt-php[1.0.0, ..., 1.5.3] require php >=8.0 -> your php version (7.4.33) does not satisfy that requirement. - haozi-team/chatgpt-php[1.6.0, ..., 1.7.0] require guzzlehttp/guzzle ^7.2.0 -> found guzzlehttp/guzzle[7.2.0, ..., 7.5.0] but it conflicts with your root composer.json require (~6.0). - Root composer.json requires haozi-team/chatgpt-php * -> satisfiable by haozi-team/chatgpt-php[1.0.0, ..., 1.7.0].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions. You can also try re-running composer require with an explicit version constraint, e.g. "composer require haozi-team/chatgpt-php:*" to figure out if any version is installable, or "composer require haozi-team/chatgpt-php:^2.1" if you know which you need.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

guzzlehttp冲突了

**Comment by hhfmiirvaxb943** [comment]
唉
